auth:
  jwt:
    issuer: team.sparta.kotlin
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        ddl-auto: create
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
        orm.jdbc.bind: trace
